"""
Django settings for articleInnovator project.

Generated by 'django-admin startproject' using Django 5.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
from datetime import timedelta


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-4+hrr&l009p%xz&y220#1e5#z0*j#=f!t5m#cl74wzrhlwj2!s"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = []

if DEBUG:
    ALLOWED_HOSTS = [
        'localhost',
    ]

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "apiApp",
    "frontendApp",
    "django_extensions",
    "rest_framework",
    "rest_framework_simplejwt",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware", 
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "apiApp.middleware.AccessControlMiddleware",  # custom middleware
]

ROOT_URLCONF = "articleInnovator.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [os.path.join(BASE_DIR, "templates")],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "articleInnovator.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

# DATABASES = {
#     "default": {
#         "ENGINE": "django.db.backends.sqlite3",
#         "NAME": BASE_DIR / "db.sqlite3",
#     }
# }

############### start additional settings ###############


DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'articleinnovators', 
        'USER': 'postgres',
        'PASSWORD': 'postgres',
        'HOST': '127.0.0.1', 
        'PORT': '5432',
    }
}
############### end additional settings ###############



# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


############### additional settings ###############

#  static path
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),
]

#  media path
MEDIA_URL='/media/'
MEDIA_ROOT=os.path.join(BASE_DIR,'media')


# smtp for mail
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_USE_TLS = True
EMAIL_PORT = 587
EMAIL_HOST_USER = 'ronakmer942@gmail.com' 
EMAIL_HOST_PASSWORD = 'onuu dkaq goyw qniz'


#  Iframe
X_FRAME_OPTIONS = 'SAMEORIGIN'


SESSION_ENGINE = 'django.contrib.sessions.backends.db'  # Using the database backend
SESSION_COOKIE_SECURE = False  # Set to True in production if using HTTPS


SIMPLE_JWT = {
    # 'ACCESS_TOKEN_LIFETIME': timedelta(minutes=5),    
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=2),  # Set to 2 hours
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
    'ROTATE_REFRESH_TOKENS': False,
    'BLACKLIST_AFTER_ROTATION': True,
    'AUTH_HEADER_TYPES': ('Bearer',),
}



REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
}


#  Iframe
X_FRAME_OPTIONS = 'SAMEORIGIN'


SESSION_ENGINE = 'django.contrib.sessions.backends.db'  # Using the database backend
SESSION_COOKIE_SECURE = False  # Set to True in production if using HTTPS
    

    

# AWS S3 settings

AWS_ACCESS_KEY_ID = 'AKIA6GBMBSQAVBQZMKF2'  
AWS_SECRET_ACCESS_KEY = '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' 
AWS_STORAGE_BUCKET_NAME = 'article-innovator-article-josn-files'  
AWS_S3_REGION_NAME = 'us-east-1' 
# AWS_S3_SIGNATURE_VERSION = 's3v4'
# AWS_DEFAULT_ACL = None
AWS_S3_CUSTOM_DOMAIN = f"{AWS_STORAGE_BUCKET_NAME}.s3.amazonaws.com"  

# wayback-files

# STORAGES = {
#     "default": {
#         "BACKEND": "storages.backends.s3.S3Storage",
#         # "BACKEND": "storages.backends.s3boto3.S3Boto3Storage",
#         "OPTIONS": {
#             "bucket_name": AWS_STORAGE_BUCKET_NAME,
#             "custom_domain": AWS_S3_CUSTOM_DOMAIN,
#             "access_key": AWS_ACCESS_KEY_ID,
#             "secret_key": AWS_SECRET_ACCESS_KEY,
#             "region_name": AWS_S3_REGION_NAME,
#         }
#     },
#     "staticfiles": {
#         "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
#         "LOCATION": "/static/",
#         'OPTIONS': {  
#             'location': BASE_DIR / 'static'
#         }
#     },
# }


STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
        "OPTIONS": {
            "location": os.path.join(BASE_DIR, "media"),
        },
    },
    "staticfiles": {
        "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
        "LOCATION": "/static/",
        "OPTIONS": {
            "location": os.path.join(BASE_DIR, "static"),
        },
    },
    "custom_s3": {
        "BACKEND": "storages.backends.s3boto3.S3Boto3Storage",
        "OPTIONS": {
            "bucket_name": AWS_STORAGE_BUCKET_NAME,
            "custom_domain": AWS_S3_CUSTOM_DOMAIN,
            "access_key": AWS_ACCESS_KEY_ID,
            "secret_key": AWS_SECRET_ACCESS_KEY,
            "region_name": AWS_S3_REGION_NAME,
        },
        # "LOCATION": "custom_files/", 
    },
}




#  image kit config
IMAGEKIT = {
    'PUBLIC_KEY': 'public_tlF7GbY5ixVQhO3I49pUgym/4lA=',
    'PRIVATE_KEY': 'private_QsF9D6YRrbJdWLn8hnZROA4HCMk=',
    'URL_ENDPOINT': 'https://ik.imagekit.io/botxbyte',
}

# settings.py
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',  # For development
        # 'BACKEND': 'django.core.cache.backends.redis.RedisCache', # Use Redis for production
        # 'LOCATION': 'redis://127.0.0.1:6379/1',  # Redis configuration
        # 'LOCATION': 'unique-snowflake',

    }
}




# ip host

# ALLOWED_HOSTS = ['http://192.168.1.3:8000', 'localhost', '192.168.1.3', '192.168.1.3','*']

# # CORS_ALLOWED_ORIGINS = [
# #         'http://siteyouwantto.allow.com',
# #         'http://anothersite.allow.com',
# #     ]

# CSRF_TRUSTED_ORIGINS = [
#         'http://siteyouwantto.allow.com',
#     ]




CORS_ALLOW_ALL_ORIGINS = True


